<?xml version="1.0" encoding="utf-8"?>


<!DOCTYPE mozi SYSTEM "GH5OGN_mozi_dtd.dtd">
<!DOCTYPE mozi [
    <!ELEMENT mozi (film*)>
    <!ELEMENT film (rendezo+, szinesz+, iro+)>
    <!ATTLIST film id ID #REQUIRED mufaj (thriller|horror|romantikus) #REQUIRED>

    <!ELEMENT rendezo (#PCDATA)>
     <!ATTLIST rendezo id ID #REQUIRED nev CDATA #IMPLIED>

    <!ELEMENT szinesz (gyerekszinesz | musicalszinesz | szinkronszinesz)*>
    <!ATTLIST szinesz id ID #REQUIRED nev CDATA #IMPLIED>
        
    <!ELEMENT gyerekszinesz (#PCDATA)>
    <!ELEMENT musicalszinesz (#PCDATA)>
    <!ELEMENT szinkronszinesz (#PCDATA)>
    <!ELEMENT iro (#PCDATA)>
    <!ATTLIST iro id ID #REQUIRED>
    
   
    

]>
<mozi>
    <film id="txn_nxm_2jb" mufaj="horror">
        <rendezo id="nzk_4xm_2jb" nev="alex"></rendezo>
        <szinesz id="u5q_4xm_2jb" nev="Madison_Ivy"></szinesz>
        <szinesz id="a"/>
          <gyerekszinesz />
          <musicalszinesz />
          <szinkronszinesz />
        </szinesz>
        <iro id="trv_4xm_2jb"/>
    </film>
</mozi>