=== ballaleventedavid/GH5OGNWebXML/GH5OGN_0924/GH5OGN_orarend.dtd
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT GH5OGN_orarend (ora+)>
<!ATTLIST ora id ID #REQUIRED tipus (ElmÃ©let|Gyakorlat) #REQUIRED>

<!ELEMENT ora (targy, idopont, helyszin, oktato, szak)>
<!ELEMENT targy (#PCDATA)>
<!ELEMENT idopont (nap, tol, ig)>
<!ELEMENT nap (#PCDATA)>
<!ELEMENT tol (#PCDATA)>
<!ELEMENT ig (#PCDATA)>
<!ELEMENT helyszin (#PCDATA)>
<!ELEMENT oktato (#PCDATA)>
<!ELEMENT szak (#PCDATA)>

=== ballaleventedavid/GH5OGNWebXML/GH5OGN_0924/GH5OGN_orarend.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE GH5OGN_orarend SYSTEM "GH5OGN_orarend.dtd">

<!DOCTYPE GH5OGN_orarend [
    <!ELEMENT GH5OGN_orarend (ora+)>
    <!ATTLIST ora id ID #REQUIRED tipus (Elmélet|Gyakorlat) #REQUIRED>
    
    <!ELEMENT ora (targy, idopont, helyszin, oktato, szak)>
    <!ELEMENT targy (#PCDATA)>
    <!ELEMENT idopont (nap, tol, ig)>
    <!ELEMENT nap (#PCDATA)>
    <!ELEMENT tol (#PCDATA)>
    <!ELEMENT ig (#PCDATA)>
    <!ELEMENT helyszin (#PCDATA)>
    <!ELEMENT oktato (#PCDATA)>
    <!ELEMENT szak (#PCDATA)>
    

]>
<GH5OGN_orarend>
    <ora id="1" tipus="Elmélet">
        <targy>Elektrotechnika-elektronika</targy>
        <idopont>
            <nap>Hétfő</nap>
            <tol>08:00</tol>
            <ig>09:50</ig>
        </idopont>
        <helyszin>3. előadó</helyszin>
        <oktato>Szabó Norbert</oktato>
        <szak>Mérnökinformatikus BSc</szak>
    </ora>

    <ora id="2" tipus="Elmélet">
        <targy>Web technológiák 1.</targy>
        <idopont>
            <nap>Hétfő</nap>
            <tol>10:00</tol>
            <ig>12:00</ig>
        </idopont>
        <helyszin>5. előadó</helyszin>
        <oktato>Dr. Agárdi Anita</oktato>
        <szak>Mérnökinformatikus BSc</szak>
    </ora>
    <ora id="3" tipus="Elmélet">
        <targy>Angol szaknyelv</targy>
        <idopont>
            <nap>Hétfő</nap>
            <tol>12:00</tol>
            <ig>14:00</ig>
        </idopont>
        <helyszin>A1/101</helyszin>
        <oktato>Dobronyi Eszter</oktato>
        <szak>Mérnökinformatikus BSc</szak>
    </ora>
    <ora id="4" tipus="Gyakorlat">
        <targy>Web technológiák 1.</targy>
        <idopont>
            <nap>Hétfő</nap>
            <tol>14:00</tol>
            <ig>16:00</ig>
        </idopont>
        <helyszin>L101</helyszin>
        <oktato>Dr. Agárdi Anita</oktato>
        <szak>Mérnökinformatikus BSc</szak>
    </ora>

    <ora id="5" tipus="Elmélet">
        <targy>Mobil programozási alapok</targy>
        <idopont>
            <nap>Hétfő</nap>
            <tol>16:00</tol>
            <ig>18:00</ig>
        </idopont>
        <helyszin>L101</helyszin>
        <oktato>Dr. Agárdi Anita</oktato>
        <szak>Mérnökinformatikus BSc</szak>
    </ora>

    <ora id="6" tipus="Gyakorlat">
        <targy>Mobil programozási alapok</targy>
        <idopont>
            <nap>Hétfő</nap>
            <tol>18:00</tol>
            <ig>20:00</ig>
        </idopont>
        <helyszin>L101</helyszin>
        <oktato>Dr. Agárdi Anita</oktato>
        <szak>Mérnökinformatikus BSc</szak>
    </ora>
    <ora id="7" tipus="Gyakorlat">
        <targy>Windows rendszergazda</targy>
        <idopont>
            <nap>Kedd</nap>
            <tol>08:00</tol>
            <ig>10:00</ig>
        </idopont>
        <helyszin>L103</helyszin>
        <oktato>Dr. Wagner György</oktato>
        <szak>Mérnökinformatikus BSc</szak>
    </ora>

    <ora id="8" tipus="Elmélet">
        <targy>Mesterséges intelligencia alapok</targy>
        <idopont>
            <nap>Kedd</nap>
            <tol>10:00</tol>
            <ig>12:00</ig>
        </idopont>
        <helyszin>E32</helyszin>
        <oktato>Kunné Dr. Tamás Judit</oktato>
        <szak>Mérnökinformatikus BSc</szak>
    </ora>

    <ora id="9" tipus="Gyakorlat">
        <targy>Mesterséges intelligencia alapok</targy>
        <idopont>
            <nap>Kedd</nap>
            <tol>12:00</tol>
            <ig>14:00</ig>
        </idopont>
        <helyszin>E32</helyszin>
        <oktato>Kunné Dr. Tamás Judit</oktato>
        <szak>Mérnökinformatikus BSc</szak>
    </ora>

    <ora id="10" tipus="Gyakorlat">
        <targy>Elektrotechnika-elektronika</targy>
        <idopont>
            <nap>Kedd</nap>
            <tol>14:00</tol>
            <ig>15:50</ig>
        </idopont>
        <helyszin>T058</helyszin>
        <oktato>Dr. Kozsely Gábor</oktato>
        <szak>Mérnökinformatikus BSc</szak>
    </ora>

    <ora id="11" tipus="Elmélet">
        <targy>Windows rendszergazda</targy>
        <idopont>
            <nap>Kedd</nap>
            <tol>16:00</tol>
            <ig>18:00</ig>
        </idopont>
        <helyszin>L103</helyszin>
        <oktato>Dr. Wagner György</oktato>
        <szak>Mérnökinformatikus BSc</szak>
    </ora>
    <ora id="12" tipus="Elmélet">
        <targy>Szoftvertechnológia</targy>
        <idopont>
            <nap>Szerda</nap>
            <tol>08:00</tol>
            <ig>10:00</ig>
        </idopont>
        <helyszin>3. előadó</helyszin>
        <oktato>Dr. Mileff Péter</oktato>
        <szak>Mérnökinformatikus BSc</szak>
    </ora>

    <ora id="13" tipus="Elmélet">
        <targy>Webes adatkezelő környezetek</targy>
        <idopont>
            <nap>Szerda</nap>
            <tol>08:00</tol>
            <ig>10:00</ig>
        </idopont>
        <helyszin>T050</helyszin>
        <oktato>Dr. Kovács László József</oktato>
        <szak>Mérnökinformatikus BSc</szak>
    </ora>

    <ora id="14" tipus="Gyakorlat">
        <targy>Szoftvertechnológia</targy>
        <idopont>
            <nap>Szerda</nap>
            <tol>10:00</tol>
            <ig>12:00</ig>
        </idopont>
        <helyszin>3. előadó</helyszin>
        <oktato>Dr. Mileff Péter</oktato>
        <szak>Mérnökinformatikus BSc</szak>
    </ora>

    <ora id="15" tipus="Gyakorlat">
        <targy>Webes adatkezelő környezetek</targy>
        <idopont>
            <nap>Szerda</nap>
            <tol>10:00</tol>
            <ig>12:00</ig>
        </idopont>
        <helyszin>L103</helyszin>
        <oktato>Dr. Bednarik László</oktato>
        <szak>Mérnökinformatikus BSc</szak>
    </ora>
</GH5OGN_orarend>
